### ISSUE TITLE
My Comments

### ISSUE THREAD

**Issue by zjedwin** [LeganAlegria/pwp-capstones#1]
Related to your `User` class:

1. The `__repre__` method is not needed.

2. In your `__repr__` method, you don't need to turn the dictionary `self.books` into a list in order to call length on it, as you do here: `temp_list = list(self.books)`. Besides that, you don't need to cast the length to a string, as you do here `number_of_books = str(len(temp_list))`. The format string works fine with numbers. So `"This works fine {}".format(10)`.

3. In your `get_average_rating` method, there are a few things:
  - In this line, `temp_list = list(self.books.values())`, it's unnecessary to cast to a list since `self.books.values()` returns a list.
  - Since some of the entries in the dictionary can be `None`, you want to check that the value is not `None` before writing `sum += value`.
  - Finally, the value that you divide by shouldn't be the number of entries in `self.books`. It should be the number of entries which are not `None`.

Related to your `Book` class:

1. You have the following two lines for 78-79:
`number_of_ratings = len(self.ratings)`
`for i in range(len(self.ratings)):`
Instead of writing `len(self.ratings)` again on the second line, use the variable that you've just defined.

2. In the final `if/else` statement of your `get_average_rating` method, although it's fine to write
`if sum > 0:`
since `sum > 0` if and only if `number_of_ratings > 0`, it's more to the point to write instead,
`if number_of_ratings > 0:`

Related to your `TomeRater` class:

1. You spend a lot of energy in your create methods making sure that you're not creating a book that already exists. You shouldn't worry about that here. You should simply create and return the item.

2. On lines 165-166, instead of writing `self.users.get(email)` and `self.users[email]`, you should define a variable to store the variable and then reuse the variable. 

3. In your `add_user` method, you're doing quite a lot of extra work. Although it is not necessary to do so, it's nice to see that you thought about the requirements of a real function like this.

4. In your `highest_rated_book` method, you have the following line:
`if book.get_average_rating() > highest_score_temp:`
The value of `highest_score_temp` initially begins at 0. So you'll have a problem when all the books have an average rating of 0. In this case you'll return the empty string erroneously. In this case, you may want to use `>=` like this
`if book.get_average_rating() >= highest_score_temp:`

5. You have a similar issue as the previous point with `most_positive_user` and `get_most_read_book`.

6. In your `get_most_read_book` method, you have a typo: You write `most__read_book = ""` when you mean to write `most_read_book = ""`.

**Comment by LeganAlegria** [comment]
Thanks for your input. I certainly will take your notes a go back to improve what I applied so I can get better with more practice.
